#!/bin/bash

binlist=(
   '~/.xinitrc i3'
   '~/.xinitrc xfce4'
)
namelist=('i3' 'xfce')

# C X
flaglist=(X X)

dialogrc='/usr/share/cdm/themes/cdm'
countfrom=0
display=0
xtty=7
locktty=no
consolekit=yes
cktimeout=30
serverargs=(-nolisten tcp)
altstartx=no
startxlog=/dev/null
