version: "3"

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        depends_on:
            - php
        volumes:
            - ~/htdocs:/code
            - ~/docker/confs/nginx.conf:/etc/nginx/conf.d/default.conf
        restart: unless-stopped

    php:
        image: php:7.3-fpm
        ports:
            - "9000:9000"
        build:
            context: ../../dockerfile/
            dockerfile: php
        volumes:
            - ~/htdocs:/code
            - ~/docker/confs/phplog.conf:/usr/local/etc/php-fpm.d/log.conf
        restart: unless-stopped

    mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=senha
            - MYSQL_DATABASE=app
        restart: unless-stopped

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
            - mysql
        ports:
            - "8082:80"
        environment:
            - PMA_HOST=mysql
        restart: unless-stopped