# phpdocker.io

version: '3.1'

services:
    web:
        container_name: nginx
        image: nginx:latest
        ports:
            - "80:80"
        links:
            - php
            - mysql
        depends_on:
            - php
        volumes:
            - ~/htdocs:/code
            - ~/docker/confs/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - nginxnet
        restart: always

    php:
        container_name: php
        image: php:7-fpm
        ports:
            - "9000:9000"
        build:
            context: ../../dockerfile/
            dockerfile: php
        volumes:
            - ~/htdocs:/code
            - ~/docker/confs/phplog.conf:/usr/local/etc/php-fpm.d/log.conf
        networks:
            - nginxnet
        restart: always

    #mysql:
    #    container_name: mysql
    #    image: mysql:latest
    mariadb:
        container_name: mariadb
        image: mariadb:latest
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        volumes:
            - ~/docker/data/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=senha
            - MYSQL_DATABASE=app
        networks:
            - nginxnet
        restart: always

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
            - mysql
        ports:
            - "8082:80"
        volumes:
            - ~/docker/confs/phpmyadmin.php:/etc/phpmyadmin/config.user.inc.php
        environment:
            - PMA_HOST=mysql
        networks:
            - nginxnet
        restart: always

networks:
    nginxnet:
