version: '3.1'

services:
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - "80:80"
        links:
            - php
            - mariadb
        depends_on:
            - php
        volumes:
            - ~/htdocs:/code
            - ~/docker/confs/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            rede:
                ipv4_address: 10.10.10.10
        restart: unless-stopped

    php:
        container_name: php
        image: php:7.3-fpm
        ports:
            - "9000:9000"
        build:
            context: ../../dockerfile/
            dockerfile: php
        volumes:
            - ~/htdocs:/code
            - ~/docker/confs/phplog.conf:/usr/local/etc/php-fpm.d/log.conf
        networks:
            rede:
                ipv4_address: 10.10.10.20
        restart: unless-stopped

    mariadb:
        container_name: mariadb
        image: mariadb:latest
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        volumes:
            - ~/docker/data/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=senha
            - MYSQL_DATABASE=app
        networks:
            rede:
                ipv4_address: 10.10.10.30
        restart: unless-stopped

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
            - mariadb
        ports:
            - "8082:80"
        volumes:
            - ~/docker/confs/phpmyadmin.php:/etc/phpmyadmin/config.user.inc.php
        environment:
            - PMA_HOST=mysql
        networks:
            rede:
                ipv4_address: 10.10.10.40
        restart: unless-stopped

networks:
    rede:
        ipam:
            driver: default
            config:
                - subnet: 10.10.10.0/24
