version: "3"

services:
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ~/gitlab:/code
            - ~/docker/confs/nginx.conf:/etc/nginx/conf.d/default.conf
            - ~/docker/certs:/etc/ssl/nginx
        #restart: "no"
        #restart: always
        #restart: on-failure
        restart: unless-stopped

    php:
        container_name: php
        image: php:fpm
        ports:
            - "9000:9000"
        build:
            context: ../../dockerfile/
            dockerfile: php
        volumes:
            - ~/gitlab:/code
            - ~/docker/confs/phplog.conf:/usr/local/etc/php-fpm.d/log.conf
            - ~/docker/confs/php.conf:/usr/local/etc/php-fpm.d/php.conf
            - ~/docker/confs/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ~/docker/confs/fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
        #restart: "no"
        #restart: always
        #restart: on-failure
        restart: unless-stopped

    nginxalt:
        container_name: nginxalt
        image: nginx:latest
        ports:
            - "8080:8080"
            - "8843:8843"
        volumes:
            - ~/sites:/code
            - ~/docker/confs/nginxalt.conf:/etc/nginx/conf.d/default.conf
            - ~/docker/certs:/etc/ssl/nginx
        #restart: "no"
        #restart: always
        #restart: on-failure
        restart: unless-stopped

    phpalt:
        container_name: phpalt
        image: php:fpm
        ports:
            - "9090:9090"
        build:
            context: ../../dockerfile/
            dockerfile: phpalt
        volumes:
            - ~/sites:/code
            - ~/docker/confs/phplog.conf:/usr/local/etc/php-fpm.d/log.conf
            - ~/docker/confs/php.conf:/usr/local/etc/php-fpm.d/php.conf
            - ~/docker/confs/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ~/docker/confs/fpm2.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
        #restart: "no"
        #restart: always
        #restart: on-failure
        restart: unless-stopped

    mysql:
        container_name: mysql
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        build:
            context: ../../dockerfile/
            dockerfile: mysql
        volumes:
            - ~/docker/data/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=senha
            - MYSQL_DATABASE=app
        #restart: "no"
        #restart: always
        #restart: on-failure
        restart: unless-stopped

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
            - mysql
        ports:
            - "8082:80"
        volumes:
            - ~/docker/confs/phpmyadmin.php:/etc/phpmyadmin/config.user.inc.php
        environment:
            - PMA_HOST=mysql
        #restart: "no"
        #restart: always
        #restart: on-failure
        restart: unless-stopped
