version: "3"

services:
    nginx-alt:
        container_name: nginx-alt
        image: nginx:latest
        ports:
            - "9090:9090"
        volumes:
            - ~/gitlab:/code
            - ~/docker/confs/nginx-alt2.conf:/etc/nginx/conf.d/default.conf
            - ~/sdm:/opt/musicas
            - /var/log/liquidsoap.log
        restart: unless-stopped

    php-alt:
        container_name: php-alt
        image: php:7.3-fpm
        ports:
            - "9292:9292"
        build:
            context: ../../dockerfile/
            dockerfile: php-alt2
        volumes:
            - ~/gitlab:/code
            - ~/docker/confs/phplog-alt.conf:/usr/local/etc/php-fpm.d/log.conf
            - ~/docker/confs/php-alt.conf:/usr/local/etc/php-fpm.d/php.conf
            - ~/docker/confs/php-alt.ini:/usr/local/etc/php/conf.d/php.ini
            - ~/sdm:/opt/musicas
            - /var/log/liquidsoap.log
        restart: unless-stopped