#!/bin/bash

res=$(echo "firefox;termite;pcmanfm;telegram;sublime;pluma;lxtask;deluge" | rofi -sep ";" -dmenu -p "Rofi Apps" -bw 0 -lines 8 -separator-style none -location 0 -width 180 -hide-scrollbar -padding 1)

if [ ! -z $res ]; then
	case $res in
		telegram) i3-msg -q exec telegram-desktop ;;
		sublime) i3-msg -q exec subl ;;
		*) i3-msg -q "exec $res" ;;
	esac
fi
